language: ruby
ruby:
  - 2.4.1

os: osx

env:
  - DB=postgres

services:
  - postgresql

  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

  test:
    adapter: postgresql
    database: travis_ci_test
