language: ruby
ruby:
  - 2.4.1

os: osx

env:
  - ENV['RAILS_ENV'] = 'test'

services:
  - postgresql

  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - nvm install v11.12.0
  - nvm use v11.12.0
  - yarn add stimulus

  test:
    adapter: postgresql
    database: travis_ci_test
